title: 我的个人网站
author: 你的名字
description: 这是我的个人博客
baseurl: ""
url: "https://www.liukexin.com"
remote_theme: pmarsceill/just-the-docs
# 开启侧边栏
nav_external_links:
  - title: 我的博客
    url: /
    hide_icon: false
# 侧边栏目录自动生成
heading_anchors: true
